
import {
    Bug,
    BugOff,
    ShieldAlert,
    ShieldCheck,
    Siren,
    AlertTriangle,
    AlertCircle,
    CircleCheck,
    CircleX,
    Code2,
    Terminal,
    Braces,
    FileCode,
    GitBranch,
    GitPullRequest,
    GitMerge,
    Monitor,
    Smartphone,
    Server,
    Database,
    Cloud,
    Cpu,
    Globe,
    Wifi,
    Lock,
    KeyRound,
    TestTube2,
    FlaskConical,
    Search,
    ScanSearch,
    Zap,
    Gauge,
    Activity,
    Wrench,
    Settings,
    Toolbox,
    Rocket,
    Package,
    Layers,
    Users,
    UserRound,
    Folder,
    ClipboardCheck,
    ListTodo,
    MessageSquare,
    Bell,
    Megaphone,
    Flag,
    Bookmark,
    Tag,
    Flame,
    Snowflake,
    Lightbulb,
    Target,
    Eye,
    LayoutDashboard,
    Bot,
    Sparkles,
    Palette,
    BookOpen,
    Puzzle,
    Component,
    Clock,
    Calendar,
} from "lucide-react";

export const TEAM_ICONS = [
    { id: "bug", label: "Bug", icon: Bug },
    { id: "bug-off", label: "Bug Fixing", icon: BugOff },
    { id: "security", label: "Security", icon: ShieldAlert },
    { id: "shield", label: "Security", icon: ShieldCheck },
    { id: "incident", label: "Incident Response", icon: Siren },
    { id: "warning", label: "Warnings", icon: AlertTriangle },
    { id: "alert", label: "Alerts", icon: AlertCircle },

    { id: "code", label: "Development", icon: Code2 },
    { id: "terminal", label: "Engineering", icon: Terminal },
    { id: "braces", label: "Programming", icon: Braces },
    { id: "file-code", label: "Code", icon: FileCode },
    { id: "git-branch", label: "Git", icon: GitBranch },
    { id: "pull-request", label: "Pull Requests", icon: GitPullRequest },
    { id: "git-merge", label: "Merging", icon: GitMerge },

    { id: "monitor", label: "Frontend", icon: Monitor },
    { id: "mobile", label: "Mobile", icon: Smartphone },
    { id: "server", label: "Backend", icon: Server },
    { id: "database", label: "Database", icon: Database },
    { id: "cloud", label: "Cloud", icon: Cloud },
    { id: "cpu", label: "Infrastructure", icon: Cpu },
    { id: "globe", label: "Web", icon: Globe },
    { id: "wifi", label: "Networking", icon: Wifi },

    { id: "lock", label: "Security", icon: Lock },
    { id: "key", label: "Authentication", icon: KeyRound },

    { id: "testing", label: "Testing", icon: TestTube2 },
    { id: "research", label: "Research", icon: FlaskConical },
    { id: "search", label: "QA", icon: Search },
    { id: "investigation", label: "Investigation", icon: ScanSearch },

    { id: "performance", label: "Performance", icon: Zap },
    { id: "metrics", label: "Metrics", icon: Gauge },
    { id: "activity", label: "Monitoring", icon: Activity },

    { id: "tools", label: "Tools", icon: Wrench },
    { id: "settings", label: "Configuration", icon: Settings },
    { id: "toolbox", label: "Engineering", icon: Toolbox },

    { id: "rocket", label: "Product", icon: Rocket },
    { id: "package", label: "Release", icon: Package },
    { id: "layers", label: "Platform", icon: Layers },

    { id: "users", label: "Team", icon: Users },
    { id: "user", label: "People", icon: UserRound },

    { id: "folder", label: "Projects", icon: Folder },
    { id: "clipboard", label: "QA", icon: ClipboardCheck },
    { id: "tasks", label: "Tasks", icon: ListTodo },

    { id: "chat", label: "Support", icon: MessageSquare },
    { id: "notifications", label: "Notifications", icon: Bell },
    { id: "announcement", label: "Announcements", icon: Megaphone },

    { id: "flag", label: "Priority", icon: Flag },
    { id: "bookmark", label: "Important", icon: Bookmark },
    { id: "tag", label: "Labels", icon: Tag },

    { id: "critical", label: "Critical", icon: Flame },
    { id: "low-priority", label: "Low Priority", icon: Snowflake },

    { id: "ideas", label: "Ideas", icon: Lightbulb },
    { id: "goals", label: "Goals", icon: Target },
    { id: "monitoring", label: "Monitoring", icon: Eye },

    { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
    { id: "automation", label: "Automation", icon: Bot },
    { id: "ai", label: "AI", icon: Sparkles },

    { id: "design", label: "Design", icon: Palette },
    { id: "documentation", label: "Documentation", icon: BookOpen },
    { id: "components", label: "Components", icon: Component },
    { id: "integrations", label: "Integrations", icon: Puzzle },

    { id: "schedule", label: "Planning", icon: Calendar },
    { id: "time", label: "Time", icon: Clock },
];